@Gomoku.Api_HostAddress = https://localhost:5191



POST {{Gomoku.Api_HostAddress}}/game

###

GET {{Gomoku.Api_HostAddress}}/game

###

GET {{Gomoku.Api_HostAddress}}/game/{code}

###

PUT {{Gomoku.Api_HostAddress}}/game/join
Content-Type: application/json

{
  //JoinGameRequest
}

###

POST {{Gomoku.Api_HostAddress}}/game/move
Content-Type: application/json

{
  //AddMoveRequest
}

###

GET {{Gomoku.Api_HostAddress}}/test

###

GET {{Gomoku.Api_HostAddress}}/waitinglist

###

DELETE {{Gomoku.Api_HostAddress}}/waitinglist/string

###

GET {{Gomoku.Api_HostAddress}}/waitinglist/count

###

POST {{Gomoku.Api_HostAddress}}/waitinglist/join
Content-Type: application/json

{
  //JoinWaitingListRequest
}

###
